version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-qt!12h#w_&x44x-_itsy5k8_#vzq^n!lcs2-b3wxkya0t18$$5"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
